const ADD_CONTACT = 'ADD_CONTACT';
const REMOVE_CONTACT = 'REMOVE_CONTACT';
const FILTER_CHANGE = 'FILTER_CHANGE';
const GET_CONTACT = 'GET_CONTACT';

export { ADD_CONTACT, REMOVE_CONTACT, FILTER_CHANGE, GET_CONTACT };
